### ISSUE TITLE
Expose version number in compiled library

### ISSUE THREAD

**Issue by mhvk** [liberfa/erfa#38]
As discussed while updating erfa to 1.3 in astropy, it would be good if we could expose the version number in the erfa library, as then we could have workarounds be used only when actually needed.  See https://github.com/astropy/astropy/pull/5418#issuecomment-254632408

**Comment by eteq** [comment]
👍 , although I'm uncertain how best to do this given that the canonical version number is stored in the `configure.ac` file instead of in the source code... If necessary it could just be another step to add to the "RELEASE" instructions (making sure they are consistent), but I would like to automate it if feasible...

**Comment by sergiopasra** [comment]
This is not difficult, a few lines of code. The problem is to convince `erfa-fetch' to include the new function in erfa.h

**Comment by sergiopasra** [comment]
This is just a proof of concept, the name of the function can be different, etc

**Comment by mhvk** [comment]
That looks good! Just to make sure I understand: with your changes in #42, the only thing that will get overridden in the current release procedures is your addition to `erfa.h`, correct? One can let `erfa-fetch` deal with that, but I feel this is a bit odd, since, at least as written, `erfa-fetch` does not know anything about erfa versions.  Another way to correct the version stuff may be to add something to `bootstrap.sh` that checks whether or not `erfa_version` already is in `erfa.h`, and adds it if not. If we go that route, we might as well do the changes of version number in `configure.ac` and `README.rst` as well...  Or, from `bootstrap.sh`, call a specific script that does the above.

@eteq - since you usually do the release, what do you think? What would make life easier?

**Comment by mhvk** [comment]
Thinking about it a bit more, it might be useful as well to expose the sofa version on which the erfa version is based as well.

**Comment by sergiopasra** [comment]
We would only need to make erfa-fetch add the definitions of our erfa custom functions into erfa.h. The actual code would in erfaversion.c would stay here in the repository

**Comment by sergiopasra** [comment]
For the SOFA version, we could make erfa-fetch add a macro (in erfam.h, perhaps?) with the SOFA version and the expose it with another function

**Comment by mhvk** [comment]
@sergiopasra - both sound good; that keeps the version stuff together.

**Comment by eteq** [comment]
Hmm, is it possible for the sofa version macro to get at the same places the erfa versions do (`configure.ac`)? Or is it bit possible to get the  custom variables not through to `config.h`?

Just trying to limit the number of places that require manual updates...

As you the need to update `erfa.h` each time, that did worry me. I always examine the diff so I'd *probably* notice the removal, but it would be better to have it baked into `erfa_fetch`. Not sure the best way to do that generally so that we don't have to keep the two in sync... But maybe we just do this one by hand because it'll probably be the only one like this?

**Comment by sergiopasra** [comment]
@eteq Yes, I can add a macro in configure so that SOFA_VERSION is set there. It has to be updated manually then.

As an alternative to the `erfa.h` update, we can include all our extra definitions in a new header, say `erfaextra.h`, and include it in `erfa.h`.  This way we isolate all possible future changes in one file under our control. `erfa-fetch` would only need to add a `#include erfaextra.h` after processing all the definitions in `sofa.h` and before the license text.

**Comment by mhvk** [comment]
I like the `erfaextra.h` idea!

**Comment by eteq** [comment]
I also like `erfaextra.h` - sounds much easier to maintain!

**Comment by eteq** [comment]
Done in #42 !
