### ISSUE TITLE
ERFA 1.7 still has version number 1.6!?

### ISSUE THREAD

**Issue by mhvk** [liberfa/erfa#62]
See https://github.com/liberfa/erfa/blob/master/src/erfaversion.c#L10

@eteq - since you did the release, it's probably easiest for you to fix...  I have a PR ready for the astropy side (indeed, that is how I found out...)

**Comment by sergiopasra** [comment]
It's not that bad because the macros are overridden in this line

https://github.com/liberfa/erfa/blob/master/src/erfaversion.c#L25

`config.h` contains the correct values from `configure`. I agree that actual disposition of the macros is confusing. They should be used only if `config.h` does not exist

**Comment by mhvk** [comment]
Ah, that's good.  I'll proceed with my PR to astropy, then.
